// Code generated by MockGen. DO NOT EDIT.
// Source: port.go
//
// Generated by this command:
//
//	mockgen -source=port.go -destination=mock/mock_port.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	domain "ai-bridge/internal/domain"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRequestRepository is a mock of RequestRepository interface.
type MockRequestRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRequestRepositoryMockRecorder
	isgomock struct{}
}

// MockRequestRepositoryMockRecorder is the mock recorder for MockRequestRepository.
type MockRequestRepositoryMockRecorder struct {
	mock *MockRequestRepository
}

// NewMockRequestRepository creates a new mock instance.
func NewMockRequestRepository(ctrl *gomock.Controller) *MockRequestRepository {
	mock := &MockRequestRepository{ctrl: ctrl}
	mock.recorder = &MockRequestRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRequestRepository) EXPECT() *MockRequestRepositoryMockRecorder {
	return m.recorder
}

// Load mocks base method.
func (m *MockRequestRepository) Load(path string) (*domain.Request, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Load", path)
	ret0, _ := ret[0].(*domain.Request)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Load indicates an expected call of Load.
func (mr *MockRequestRepositoryMockRecorder) Load(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Load", reflect.TypeOf((*MockRequestRepository)(nil).Load), path)
}

// Remove mocks base method.
func (m *MockRequestRepository) Remove(path string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Remove", path)
}

// Remove indicates an expected call of Remove.
func (mr *MockRequestRepositoryMockRecorder) Remove(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*MockRequestRepository)(nil).Remove), path)
}

// MockRequestWriter is a mock of RequestWriter interface.
type MockRequestWriter struct {
	ctrl     *gomock.Controller
	recorder *MockRequestWriterMockRecorder
	isgomock struct{}
}

// MockRequestWriterMockRecorder is the mock recorder for MockRequestWriter.
type MockRequestWriterMockRecorder struct {
	mock *MockRequestWriter
}

// NewMockRequestWriter creates a new mock instance.
func NewMockRequestWriter(ctrl *gomock.Controller) *MockRequestWriter {
	mock := &MockRequestWriter{ctrl: ctrl}
	mock.recorder = &MockRequestWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRequestWriter) EXPECT() *MockRequestWriterMockRecorder {
	return m.recorder
}

// Save mocks base method.
func (m *MockRequestWriter) Save(bridgeDir string, req *domain.Request) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", bridgeDir, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockRequestWriterMockRecorder) Save(bridgeDir, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockRequestWriter)(nil).Save), bridgeDir, req)
}

// MockHistoryRepository is a mock of HistoryRepository interface.
type MockHistoryRepository struct {
	ctrl     *gomock.Controller
	recorder *MockHistoryRepositoryMockRecorder
	isgomock struct{}
}

// MockHistoryRepositoryMockRecorder is the mock recorder for MockHistoryRepository.
type MockHistoryRepositoryMockRecorder struct {
	mock *MockHistoryRepository
}

// NewMockHistoryRepository creates a new mock instance.
func NewMockHistoryRepository(ctrl *gomock.Controller) *MockHistoryRepository {
	mock := &MockHistoryRepository{ctrl: ctrl}
	mock.recorder = &MockHistoryRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHistoryRepository) EXPECT() *MockHistoryRepositoryMockRecorder {
	return m.recorder
}

// Append mocks base method.
func (m *MockHistoryRepository) Append(bridgeDir string, req *domain.Request) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Append", bridgeDir, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// Append indicates an expected call of Append.
func (mr *MockHistoryRepositoryMockRecorder) Append(bridgeDir, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Append", reflect.TypeOf((*MockHistoryRepository)(nil).Append), bridgeDir, req)
}

// Load mocks base method.
func (m *MockHistoryRepository) Load(bridgeDir string) ([]*domain.Request, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Load", bridgeDir)
	ret0, _ := ret[0].([]*domain.Request)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Load indicates an expected call of Load.
func (mr *MockHistoryRepositoryMockRecorder) Load(bridgeDir any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Load", reflect.TypeOf((*MockHistoryRepository)(nil).Load), bridgeDir)
}

// MockScriptStore is a mock of ScriptStore interface.
type MockScriptStore struct {
	ctrl     *gomock.Controller
	recorder *MockScriptStoreMockRecorder
	isgomock struct{}
}

// MockScriptStoreMockRecorder is the mock recorder for MockScriptStore.
type MockScriptStoreMockRecorder struct {
	mock *MockScriptStore
}

// NewMockScriptStore creates a new mock instance.
func NewMockScriptStore(ctrl *gomock.Controller) *MockScriptStore {
	mock := &MockScriptStore{ctrl: ctrl}
	mock.recorder = &MockScriptStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockScriptStore) EXPECT() *MockScriptStoreMockRecorder {
	return m.recorder
}

// Remove mocks base method.
func (m *MockScriptStore) Remove(path string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Remove", path)
}

// Remove indicates an expected call of Remove.
func (mr *MockScriptStoreMockRecorder) Remove(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*MockScriptStore)(nil).Remove), path)
}

// Save mocks base method.
func (m *MockScriptStore) Save(build func(string) string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", build)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Save indicates an expected call of Save.
func (mr *MockScriptStoreMockRecorder) Save(build any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockScriptStore)(nil).Save), build)
}

// MockDirVerifier is a mock of DirVerifier interface.
type MockDirVerifier struct {
	ctrl     *gomock.Controller
	recorder *MockDirVerifierMockRecorder
	isgomock struct{}
}

// MockDirVerifierMockRecorder is the mock recorder for MockDirVerifier.
type MockDirVerifierMockRecorder struct {
	mock *MockDirVerifier
}

// NewMockDirVerifier creates a new mock instance.
func NewMockDirVerifier(ctrl *gomock.Controller) *MockDirVerifier {
	mock := &MockDirVerifier{ctrl: ctrl}
	mock.recorder = &MockDirVerifierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDirVerifier) EXPECT() *MockDirVerifierMockRecorder {
	return m.recorder
}

// IsDir mocks base method.
func (m *MockDirVerifier) IsDir(path string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsDir", path)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsDir indicates an expected call of IsDir.
func (mr *MockDirVerifierMockRecorder) IsDir(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsDir", reflect.TypeOf((*MockDirVerifier)(nil).IsDir), path)
}

// MockLauncher is a mock of Launcher interface.
type MockLauncher struct {
	ctrl     *gomock.Controller
	recorder *MockLauncherMockRecorder
	isgomock struct{}
}

// MockLauncherMockRecorder is the mock recorder for MockLauncher.
type MockLauncherMockRecorder struct {
	mock *MockLauncher
}

// NewMockLauncher creates a new mock instance.
func NewMockLauncher(ctrl *gomock.Controller) *MockLauncher {
	mock := &MockLauncher{ctrl: ctrl}
	mock.recorder = &MockLauncherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLauncher) EXPECT() *MockLauncherMockRecorder {
	return m.recorder
}

// Launch mocks base method.
func (m *MockLauncher) Launch(cwd, scriptPath string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Launch", cwd, scriptPath)
	ret0, _ := ret[0].(error)
	return ret0
}

// Launch indicates an expected call of Launch.
func (mr *MockLauncherMockRecorder) Launch(cwd, scriptPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Launch", reflect.TypeOf((*MockLauncher)(nil).Launch), cwd, scriptPath)
}

// MockWatcher is a mock of Watcher interface.
type MockWatcher struct {
	ctrl     *gomock.Controller
	recorder *MockWatcherMockRecorder
	isgomock struct{}
}

// MockWatcherMockRecorder is the mock recorder for MockWatcher.
type MockWatcherMockRecorder struct {
	mock *MockWatcher
}

// NewMockWatcher creates a new mock instance.
func NewMockWatcher(ctrl *gomock.Controller) *MockWatcher {
	mock := &MockWatcher{ctrl: ctrl}
	mock.recorder = &MockWatcherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWatcher) EXPECT() *MockWatcherMockRecorder {
	return m.recorder
}

// Watch mocks base method.
func (m *MockWatcher) Watch(ctx context.Context) (<-chan string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Watch", ctx)
	ret0, _ := ret[0].(<-chan string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Watch indicates an expected call of Watch.
func (mr *MockWatcherMockRecorder) Watch(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Watch", reflect.TypeOf((*MockWatcher)(nil).Watch), ctx)
}

// MockBridgeDirEnsurer is a mock of BridgeDirEnsurer interface.
type MockBridgeDirEnsurer struct {
	ctrl     *gomock.Controller
	recorder *MockBridgeDirEnsurerMockRecorder
	isgomock struct{}
}

// MockBridgeDirEnsurerMockRecorder is the mock recorder for MockBridgeDirEnsurer.
type MockBridgeDirEnsurerMockRecorder struct {
	mock *MockBridgeDirEnsurer
}

// NewMockBridgeDirEnsurer creates a new mock instance.
func NewMockBridgeDirEnsurer(ctrl *gomock.Controller) *MockBridgeDirEnsurer {
	mock := &MockBridgeDirEnsurer{ctrl: ctrl}
	mock.recorder = &MockBridgeDirEnsurerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBridgeDirEnsurer) EXPECT() *MockBridgeDirEnsurerMockRecorder {
	return m.recorder
}

// Ensure mocks base method.
func (m *MockBridgeDirEnsurer) Ensure(dir string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ensure", dir)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ensure indicates an expected call of Ensure.
func (mr *MockBridgeDirEnsurerMockRecorder) Ensure(dir any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ensure", reflect.TypeOf((*MockBridgeDirEnsurer)(nil).Ensure), dir)
}

// MockCommandLocator is a mock of CommandLocator interface.
type MockCommandLocator struct {
	ctrl     *gomock.Controller
	recorder *MockCommandLocatorMockRecorder
	isgomock struct{}
}

// MockCommandLocatorMockRecorder is the mock recorder for MockCommandLocator.
type MockCommandLocatorMockRecorder struct {
	mock *MockCommandLocator
}

// NewMockCommandLocator creates a new mock instance.
func NewMockCommandLocator(ctrl *gomock.Controller) *MockCommandLocator {
	mock := &MockCommandLocator{ctrl: ctrl}
	mock.recorder = &MockCommandLocatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCommandLocator) EXPECT() *MockCommandLocatorMockRecorder {
	return m.recorder
}

// LookPath mocks base method.
func (m *MockCommandLocator) LookPath(file string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LookPath", file)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LookPath indicates an expected call of LookPath.
func (mr *MockCommandLocatorMockRecorder) LookPath(file any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LookPath", reflect.TypeOf((*MockCommandLocator)(nil).LookPath), file)
}

// MockDirInspector is a mock of DirInspector interface.
type MockDirInspector struct {
	ctrl     *gomock.Controller
	recorder *MockDirInspectorMockRecorder
	isgomock struct{}
}

// MockDirInspectorMockRecorder is the mock recorder for MockDirInspector.
type MockDirInspectorMockRecorder struct {
	mock *MockDirInspector
}

// NewMockDirInspector creates a new mock instance.
func NewMockDirInspector(ctrl *gomock.Controller) *MockDirInspector {
	mock := &MockDirInspector{ctrl: ctrl}
	mock.recorder = &MockDirInspectorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDirInspector) EXPECT() *MockDirInspectorMockRecorder {
	return m.recorder
}

// EnsureWritable mocks base method.
func (m *MockDirInspector) EnsureWritable(dir string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnsureWritable", dir)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnsureWritable indicates an expected call of EnsureWritable.
func (mr *MockDirInspectorMockRecorder) EnsureWritable(dir any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnsureWritable", reflect.TypeOf((*MockDirInspector)(nil).EnsureWritable), dir)
}

// StatDir mocks base method.
func (m *MockDirInspector) StatDir(path string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StatDir", path)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StatDir indicates an expected call of StatDir.
func (mr *MockDirInspectorMockRecorder) StatDir(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StatDir", reflect.TypeOf((*MockDirInspector)(nil).StatDir), path)
}

// MockExecutable is a mock of Executable interface.
type MockExecutable struct {
	ctrl     *gomock.Controller
	recorder *MockExecutableMockRecorder
	isgomock struct{}
}

// MockExecutableMockRecorder is the mock recorder for MockExecutable.
type MockExecutableMockRecorder struct {
	mock *MockExecutable
}

// NewMockExecutable creates a new mock instance.
func NewMockExecutable(ctrl *gomock.Controller) *MockExecutable {
	mock := &MockExecutable{ctrl: ctrl}
	mock.recorder = &MockExecutableMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExecutable) EXPECT() *MockExecutableMockRecorder {
	return m.recorder
}

// Path mocks base method.
func (m *MockExecutable) Path() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Path")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Path indicates an expected call of Path.
func (mr *MockExecutableMockRecorder) Path() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Path", reflect.TypeOf((*MockExecutable)(nil).Path))
}

// MockAgentInstaller is a mock of AgentInstaller interface.
type MockAgentInstaller struct {
	ctrl     *gomock.Controller
	recorder *MockAgentInstallerMockRecorder
	isgomock struct{}
}

// MockAgentInstallerMockRecorder is the mock recorder for MockAgentInstaller.
type MockAgentInstallerMockRecorder struct {
	mock *MockAgentInstaller
}

// NewMockAgentInstaller creates a new mock instance.
func NewMockAgentInstaller(ctrl *gomock.Controller) *MockAgentInstaller {
	mock := &MockAgentInstaller{ctrl: ctrl}
	mock.recorder = &MockAgentInstallerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAgentInstaller) EXPECT() *MockAgentInstallerMockRecorder {
	return m.recorder
}

// Install mocks base method.
func (m *MockAgentInstaller) Install(binaryPath, cli, launcher string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Install", binaryPath, cli, launcher)
	ret0, _ := ret[0].(error)
	return ret0
}

// Install indicates an expected call of Install.
func (mr *MockAgentInstallerMockRecorder) Install(binaryPath, cli, launcher any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Install", reflect.TypeOf((*MockAgentInstaller)(nil).Install), binaryPath, cli, launcher)
}
