// Package port declares the interfaces (ports) that the use case layer depends
// on for layer-crossing side effects.
//
// Ports are owned by the inner application layer and implemented by the outer
// infrastructure layer, inverting the dependency so that side effects
// (filesystem, process, environment) can be mocked in tests. Naming a call site
// argument or struct field with a port.* type makes it explicit that the call
// crosses a boundary rather than invoking the use case's own method. Mocks are
// generated by mockgen via the directive below.
package port

import (
	"context"

	"ai-bridge/internal/domain"
)

//go:generate go tool mockgen -source=port.go -destination=mock/mock_port.go -package=mock

// RequestRepository loads and removes bridge request files.
type RequestRepository interface {
	// Load reads, deserializes and validates the request at path.
	Load(path string) (*domain.Request, error)
	// Remove deletes the consumed request file, ignoring errors.
	Remove(path string)
}

// RequestWriter writes a request back into the bridge directory so the running
// daemon consumes it through its existing watcher/launcher path (used by replay).
type RequestWriter interface {
	// Save atomically writes req as request.json inside bridgeDir.
	Save(bridgeDir string, req *domain.Request) error
}

// HistoryRepository persists and reads the append-only request history.
type HistoryRepository interface {
	// Append records req as a new entry in the history under bridgeDir.
	Append(bridgeDir string, req *domain.Request) error
	// Load reads all history entries under bridgeDir, newest first.
	Load(bridgeDir string) ([]*domain.Request, error)
}

// ScriptStore persists a generated launch script to a runnable location.
type ScriptStore interface {
	// Save creates the script file, then calls build with the final path to
	// obtain the contents (the path is needed for the self-deleting line),
	// writes them and makes the file executable. It returns the script path.
	Save(build func(scriptPath string) string) (path string, err error)
	// Remove deletes a previously saved script, ignoring errors.
	Remove(path string)
}

// DirVerifier reports whether a path is an existing directory.
type DirVerifier interface {
	IsDir(path string) bool
}

// Launcher opens a new terminal and runs a script in the given directory.
type Launcher interface {
	Launch(cwd, scriptPath string) error
}

// Watcher emits the path of each consumed request file on the returned channel
// until ctx is cancelled, at which point the channel is closed.
type Watcher interface {
	Watch(ctx context.Context) (<-chan string, error)
}

// BridgeDirEnsurer ensures the bridge directory exists.
type BridgeDirEnsurer interface {
	Ensure(dir string) error
}

// CommandLocator resolves an executable in PATH.
type CommandLocator interface {
	LookPath(file string) (string, error)
}

// DirInspector inspects a directory for diagnostics.
type DirInspector interface {
	// StatDir reports whether path is a directory; err is non-nil when the path
	// cannot be stat'd (e.g. it does not exist).
	StatDir(path string) (isDir bool, err error)
	// EnsureWritable returns an error if a file cannot be created in dir.
	EnsureWritable(dir string) error
}

// Executable resolves the absolute path of the running binary.
type Executable interface {
	Path() (string, error)
}

// AgentInstaller installs and loads the launchd agent for the given binary.
type AgentInstaller interface {
	Install(binaryPath, cli, launcher string) error
}
