name: "[CI] Scaffold"
permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    paths:
      - "scripts/scaffold/**"
      - .github/workflows/ci-go-module.yml
      - mise.toml

jobs:
  ci:
    uses: ./.github/workflows/ci-go-module.yml
    with:
      module: scaffold
