name: CI go-verify
permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    paths:
      - "scripts/go-verify/**"
      - mise.toml

jobs:
  ci:
    uses: ./.github/workflows/go_module_ci.yml
    with:
      module: go-verify
