name: Lint Stylua
permissions:
  contents: read

on:
  pull_request:
    paths:
      - "**/*.lua"
      - .github/workflows/lint_stylua.yml

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@29eef336d9b2848a0b548edc03f92a220660cdb8 # stable

      - name: Install stylua
        run: cargo install stylua

      - name: Run stylua check
        run: stylua --check .
